export { PrismaClient } from '@prisma/client';
export type {
  Organization,
  Tenant,
  User,
  ApiKey,
  Agent,
  StorageVault,
  BackupPolicy,
  AgentPolicy,
  BackupJob,
  Snapshot,
  RestoreJob,
  AlertRule,
  Alert,
  AuditLog,
  UserRole,
  AgentStatus,
  OsType,
  StorageType,
  BackupType,
  JobStatus,
  RestoreType,
  AlertType,
} from '@prisma/client';
